services:
  mongodb:
    image: mongo:latest
    container_name: alpha
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_COLLECTION: ${MONGO_INITDB_COLLECTION}
    ports:
      - 27017:27017
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d
      - ./data:/data/db
      - ./logs:/var/log/mongodb
